name: Tests

on:
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - main
            - master
            - develop
            - dev/*
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - main
            - master
            - develop
            - dev/*

jobs:
    call-tests:
        uses: iMattPro/test-framework/.github/workflows/tests.yml@experimental-3.3.x
        with:
            EXTNAME: phpbb/webpushnotifications # Your extension vendor/package name
            SNIFF: 1             # Run code sniffer on your code? 1 or 0
            IMAGE_ICC: 0         # Run icc profile sniffer on your images? 1 or 0
            EPV: 1               # Run EPV (Extension Pre Validator) on your code? 1 or 0
            EXECUTABLE_FILES: 0  # Run check for executable files? 1 or 0
            CODECOV: 0           # Run code coverage via codecov? 1 or 0
            PHPBB_BRANCH: 3.3.x  # The phpBB branch to run tests on
            ALL_PHP_VERSIONS: '["7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]' # [Optional] array of all major.minor PHP versions to test
            MIN_PHP_VERSION: '7.3'  # [Optional] Your extension's PHP level (usually the minimum PHP version supported)
            RUN_NPM_INSTALL: 1      # [Optional] Install NPM/Node dependencies if your extension needs them during testing
            RUN_COMPOSER_INSTALL: 1 # [Optional] Install composer dependencies if your extension needs them during testing
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Do not change this
