name: Tests

on:
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - main
            - dev/*
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - main
            - dev/*

jobs:
    call-tests:
        name: Extension tests
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
        with:
            EXTNAME: phpbb/webpushnotifications # Your extension vendor/package name
            EXECUTABLE_FILES: 0
            RUN_NPM_INSTALL: 1
            RUN_COMPOSER_INSTALL: 1
            PHP_VERSION_MATRIX: '["7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]'
            PRIMARY_PHP_VERSION: '7.3'
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Do not change this
